// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPoYHeC_vnFgJlwqncZ1-3Wg4xOOLLAXQ',
    appId: '1:681030981373:web:8e2e118e6c1da26684d094',
    messagingSenderId: '681030981373',
    projectId: 'hive-9cb29',
    authDomain: 'hive-9cb29.firebaseapp.com',
    storageBucket: 'hive-9cb29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABZM61RdzvEMmkQaJDW-zK8pizs0Qr4EI',
    appId: '1:681030981373:android:13ed81f5c11ce85f84d094',
    messagingSenderId: '681030981373',
    projectId: 'hive-9cb29',
    storageBucket: 'hive-9cb29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY3i4LsIrV1ZPhrgL051J0v1n-51SZGqs',
    appId: '1:681030981373:ios:deb8a688a02fff4984d094',
    messagingSenderId: '681030981373',
    projectId: 'hive-9cb29',
    storageBucket: 'hive-9cb29.appspot.com',
    iosClientId: '681030981373-2dupp74vj03l0j9bcm9n8njrqbdj28ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.hive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY3i4LsIrV1ZPhrgL051J0v1n-51SZGqs',
    appId: '1:681030981373:ios:deb8a688a02fff4984d094',
    messagingSenderId: '681030981373',
    projectId: 'hive-9cb29',
    storageBucket: 'hive-9cb29.appspot.com',
    iosClientId: '681030981373-2dupp74vj03l0j9bcm9n8njrqbdj28ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.hive',
  );
}
